david-allison/manx-corpus-search

CorpusSearch/Controllers/IMuseumNewspaperController.cs
CorpusSearch/Service/IMuseumNewspaperService.cs

Extracts the logic from newspaper -> link from our source
Allows an internal redirect that we can change if required
Related: #54 #52

feat: endpoint linking to newspaper image

---

CorpusSearch/ClientApp/package-lock.json
CorpusSearch/ClientApp/package.json
CorpusSearch/ClientApp/src/App.test.tsx
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/MainSearchResults.tsx
CorpusSearch/ClientApp/src/components/NavMenu.tsx
CorpusSearch/ClientApp/src/index.tsx
CorpusSearch/ClientApp/src/registerServiceWorker.ts

Removes all instances of: `// @ts-expect-error`
* import -> require
npm i --save-dev @types/react-highlight-words
npm i --save-dev @types/react-dom
npm i --save-dev @types/jest
npm i -D @types/node

fix: typescript errors

---

CorpusSearch/ClientApp/src/App.tsx
CorpusSearch/ClientApp/src/api/SearchWorkApi.ts
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/MainSearchResults.tsx

missed some: `@ts-expect-error`
* missed 'notes' param
* exact no longer needed
* colSpan needs a number
* label for -> label htmlFor

refactor: fix compiler errors

---

CorpusSearch/ClientApp/src/components/FetchDataDocument.css
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx

Highlight the manx if searching english and vice-versa

feat: highlight translation

---

CorpusSearch/Views/Browse/Index.cshtml

Add more margin between touch targets
Google search console flagged this page for mobile

fix(Browse): make responsive

---

CorpusSearch/ClientApp/src/components/AdvancedOptions.tsx
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/Home.css
CorpusSearch/ClientApp/src/components/Home.tsx
CorpusSearch/ClientApp/src/components/ManxEnglishSelector.tsx

Use a switch for Manx/English
Move 'Match' to advanced options

redesign: search

---

CorpusSearch/ClientApp/package-lock.json
CorpusSearch/ClientApp/package.json

Menu was left-aligned. Caused by a breaking reactstrap change
downgrade to reactstrap 8

fix(Mobile): menu alignment

---

CorpusSearch/ClientApp/src/components/Home.tsx

feat(Home): Make the search language (en/gv) selectable in the URL

---

CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/Home.tsx
CorpusSearch/ClientApp/src/components/ManxEnglishSelector.tsx

Was incorrect when loading from a URL

fix: initial value of ManxEnglishSelector

---

CorpusSearch/ClientApp/src/api/DictionaryApi.ts
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/Controllers/DictionaryController.cs

Currently only Cregeen - and the data isn't great
See: https://github.com/david-allison/cregeen-manx-dictionary-data

feat: tap a word for dictionary definition

---

CorpusSearch/ClientApp/package-lock.json
CorpusSearch/ClientApp/package.json
CorpusSearch/ClientApp/src/App.tsx
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/Home.tsx

Tech demo to reduce bundle size

feat: lazy load bundles

---

CorpusSearch/ClientApp/src/App.tsx
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/Home.tsx

This reverts commit 9c6a59c3e50ea33673910c2174ee3b2682523048.
Tech demo - due to the small size of the app (and shared components), this added about 100ms to page load

Revert "feat: lazy load bundle"

---

CorpusSearch/Model/IDocument.cs
CorpusSearch/Views/Browse/Index.cshtml

feat: add dates to 'Browse'

---

CorpusSearch.Test/QueryBase.cs
CorpusSearch/ClientApp/src/api/SearchWorkApi.ts
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/Controllers/SearchController.cs
CorpusSearch/Model/Document.cs
CorpusSearch/Model/IDocument.cs
CorpusSearch/Service/DocumentSearchService2.cs

feat: Original on left

---

CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/utils/Selection.ts

And avoid word lookup on English texts

feat: allow word lookup on selections

---

CorpusSearch.Test/QueryBase.cs
CorpusSearch/ClientApp/src/api/SearchWorkApi.ts
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/Controllers/SearchController.cs
CorpusSearch/Dependencies/Lucene/LuceneIndex.cs
CorpusSearch/Model/Document.cs
CorpusSearch/Model/IDocument.cs
CorpusSearch/Service/DocumentSearchService2.cs

feat: Link to page in Google Books

---

CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/Controllers/MetadataController.cs

* Fix 'online source' (Homilies)
* remove "googleBooksId" from "additional data" (not typically relevant)

fix(Metadata): online sources

---

CorpusSearch/Controllers/SearchController.cs
CorpusSearch/Startup.cs

* Make case-insensitive
* Name dictionary
Requested in meeting

Fix: 'translation' dictionary

---

CorpusSearch/Controllers/TagsController.cs
CorpusSearch/Model/IDocument.cs
CorpusSearch/Service/IMuseumNewspaperService.cs
CorpusSearch/Views/Browse/Tags.cshtml
CorpusSearch/Views/Browse/ViewTag.cshtml

This is a sketch of the functionality to allow browsing by tag
We define three categories:
* Carn
* Noon as Noal
* Newspapers
And allow a user to list texts from these

feat: Tags

---

CorpusSearch/ClientApp/src/components/Home.tsx
CorpusSearch/ClientApp/src/components/NavMenu.tsx
CorpusSearch/Controllers/MailingListController.cs
CorpusSearch/Views/MailingList.cshtml

Set up using mailjet to our Google Group
This wasn't fun - the form designer was bad and needs more work
Also linked our privacy policy (on the mailing list page)

feat: Mailing List

---

CorpusSearch/Views/Browse/Browse.cshtml

left-justify text on 'Browse'

---

CorpusSearch/Controllers/SearchController.cs

fix; dictionary bug

---

CorpusSearch/ClientApp/public/service-worker.js
CorpusSearch/ClientApp/src/components/Home.tsx
CorpusSearch/ClientApp/src/index.tsx

Reverts david-allison/manx-corpus-search#151

Revert "Fix service worker/reactivate app"

---

CorpusSearch/ClientApp/src/App.tsx
CorpusSearch/ClientApp/src/components/BackChevron.tsx
CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx
CorpusSearch/ClientApp/src/components/Home.tsx
CorpusSearch/ClientApp/src/components/Layout.tsx
CorpusSearch/ClientApp/src/components/MainSearchResults.tsx
CorpusSearch/ClientApp/src/components/NavMenu.css
CorpusSearch/ClientApp/src/components/NavMenu.tsx

* Back goes back
* Tapping the logo goes to the home (typically 'back')
* Open Dictionary/Browse in new pages (non-React pages)

Improve navigation + back button

---

CorpusSearch/ClientApp/src/components/FetchDataDocument.tsx

This provides a better loading UX

Don't prefill "Work Search" title

---

CorpusSearch/ClientApp/src/api/Matches.ts
CorpusSearch/ClientApp/src/components/MainSearchResults.tsx
CorpusSearch/ClientApp/src/components/TranslationList.tsx
CorpusSearch/ClientApp/src/utils/Promise.ts
CorpusSearch/Controllers/SearchController.cs
CorpusSearch/Dependencies/Lucene/LuceneIndex.cs
CorpusSearch/Model/DocumentLine.cs
CorpusSearch/Model/SpanCollection.cs

* Fixes the date if the year is the same

feat(Home): Allow searching through all matches

---

CorpusSearch/ClientApp/src/components/NavMenu.tsx

Requirement of Jeebin.
I'd prefer to move this to the home of gaelg.im once it's up & running

Add "Translations" link

---

CorpusSearch/Controllers/TagsController.cs

fix typo: Gaal => Gael

---

CorpusSearch/ClientApp/src/api/CorpusStatistics.ts
CorpusSearch/ClientApp/src/components/Home.tsx
CorpusSearch/Controllers/StatisticsController.cs
CorpusSearch/Dependencies/Lucene/LuceneIndex.cs
CorpusSearch/Dependencies/Searcher.cs
CorpusSearch/Service/CsvUtils.cs
CorpusSearch/Startup.cs

* Display unique words on the home page
* Allows a user to download unique words via `/Statistics/TermFrequency/gv`

feat: display & download term frequency/unique words

---

CorpusSearch.Test/QueryParserTest.cs
CorpusSearch/Dependencies/csly/SearchParser.cs

fix: searching for words prefixed with 'or'

---

CorpusSearch/ClientApp/src/components/ComparisonTable.tsx
CorpusSearch/ClientApp/src/utils/Selection.ts

* Fix selection of multiple words
* Don't perform a dictionary search if more than 4 words are available: allowing a user to more easily copy/paste

Fixes: Dictionary

---

CorpusSearch/ClientApp/src/App.tsx
CorpusSearch/ClientApp/src/routes/BitPlayer.tsx

For use in simple timestamping
* Fixes #186

Add BitPlayer route

---

CorpusSearch/ClientApp/src/routes/BitPlayer.tsx

Add seek functionality for YouTube

---

CorpusSearch/ClientApp/src/routes/BitPlayer.tsx

Fixes https://github.com/david-allison/manx-corpus-search/issues/194
Preliminary attempt, not totally working but can do the basic loop

Initial attempt at YouTube looping

---

CorpusSearch/ClientApp/src/routes/BitPlayer.tsx

* Fixes #195 
* Couldn't quite the buttons to line up perfectly without resorting to setting a style

Add Time increment buttons

---

CorpusSearch/ClientApp/src/utils/Selection.ts

Fix highlighting search issue

---

CorpusSearch/Services/OpenDataLoader.cs
CorpusSearch/Startup.cs
CorpusSearch/appsettings.Development.json

Add LoadConfig class

---

.github/workflows/deploy-image.yml

Fixes https://github.com/david-allison/manx-corpus-search/actions/runs/8991534593/job/24699364748

fix: write id-token for attestation

---

.github/workflows/test.yml
CorpusSearch.Test/CorpusSearch.Test.csproj
CorpusSearch/CorpusSearch.csproj

build(deps): remove .net core 6

---

CorpusSearch/ClientApp/src/components/NewDocList.tsx
CorpusSearch/newdocs

And run from --since=six-months-ago as well to make it to ten items

Display Recently Uploaded instead of Changed

---

CorpusSearch.Test/UnitTest1.cs
CorpusSearch/Extensions/NormalizationExtensions.cs

Added a test for NormalizeMicrosoftWordQuotes, then refactored the code a bit to use a Dictionary

Refactor normalize quotes

---

CorpusSearch.Test/CorpusSearch.Test.csproj
CorpusSearch.Test/UnitTest1.cs
CorpusSearch/CorpusSearch.csproj

EXCEPT CsvHelper - compile changes required
* https://github.com/david-allison/manx-corpus-search/issues/227

NuGet: Update packages in solution

---

CorpusSearch/Model/CorpusSearchWorkQuery.cs

When I was searching for matches, this got in the way

increase maximum query length

---

CorpusSearch/CorpusSearch.csproj

deps: System.Text.Json

---

CorpusSearch/ClientApp/package-lock.json

`npx update-browserslist-db@latest`

build(deps): update `caniuse-lite`
